name: Genel_Liste_Tarayici
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  tara_ve_kaydet:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Depoyu Al
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Paketleri Yukle
        run: pip install requests

      - name: Sunuculari Tara
        run: python liste_tarama.py

      - name: Githuba Gonder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "TaramaBotu"
          git add atv.m3u
          git commit -m "Liste guncellendi" || exit 0
          git push
