name: ATV_HD_Hunter_TR
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup_Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install_Requests
        run: pip install requests
      - name: Run_Bot
        run: python atv.py
      - name: Commit_and_Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Bot"
          git add atv.m3u
          git commit -m "TR Link & Token Refresh" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
