name: ATV IDM Sniffer

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sniff-link:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Chrome ve Driver Kur (Sniffer icin)
        run: |
          pip install selenium webdriver-manager
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: IDM Modunda Calistir
        run: python atv.py

      - name: Linki Kaydet ve Gonder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add atv.m3u
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Taze Link YakalandÄ±"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "Link hala taze, degismemis."
          fi
