name: ATV Link Guncelleme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-link:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerekli Kütüphaneyi Yükle
        run: pip install requests

      - name: Botu Calistir
        run: python atv.py

      - name: Degisiklikleri Kaydet ve Yukle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add atv.m3u
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "ATV Linki Guncellendi"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "Herhangi bir degisiklik yok, atlanıyor."
          fi
