name: ATV_Chain_Hunter
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  hunt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup_Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install_Requests
        run: pip install requests
      - name: Run_Hunter
        run: python atv.py
      - name: Save_and_Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Bot"
          git add atv.m3u
          git commit -m "Chain Update" || exit 0
          git push
